### ISSUE TITLE
Using a basicauth authentication middleware in front of the api

### ISSUE THREAD

**Issue by Wobak** [fluzzi/traefik-frontend#1]
Hello ! 

I am trying to have a nice frontend for my traefik routers, and I saw on reddit that you did that yourself here :)

I'm building the compose here, and I built my api a bit more securely than the default one from traefik, by putting a middleware like this : 
```
http:
  routers:
    dashboard:
      rule: "Host(`traefik.home.arpa`)"
      service: "api@internal"
      entrypoints: "websecure"
      middlewares: "auth-dashboard"
      tls: true
  middlewares:
    auth-dashboard:
      basicauth:
        users: "_myuser:myredactedsuperpassword_"
```

And then, when I setup your container, I'm getting 0 entries : 

![Image](https://github.com/user-attachments/assets/f15c4eaa-2327-4b27-896b-d1d66010ae6f)

I guess that it's because it can't login to the API URL I've given it.

Is there way to add basic auth to your program and provide it through env variables for example or in the config file ?
